---
- name: "Certificates - Install mkcert"
  become: true
  ansible.builtin.shell:
    cmd: |-
      echo "{{ ansible_become_pass }}" | sudo -S mkcert -install

- name: "Certificates - Create mkcert wildcards"
  become: true
  become_user: "{{ k3s_user }}"
  ansible.builtin.shell:
    cmd: |-
      mkcert \
        -cert-file {{ k3s_installation_path }}/_wildcard.{{ k3s_wildcard_domain }}.pem \
        -key-file {{ k3s_installation_path }}/_wildcard.{{ k3s_wildcard_domain }}-key.pem \
      "*.{{ k3s_wildcard_domain }}"

- name: "Certificates - Slurp wildcard certificate"
  ansible.builtin.slurp:
    src: "{{ k3s_installation_path }}/_wildcard.{{ k3s_wildcard_domain }}.pem"
  register: wildcard_cert

- name: "Certificates - Slurp wildcard key"
  ansible.builtin.slurp:
    src: "{{ k3s_installation_path }}/_wildcard.{{ k3s_wildcard_domain }}-key.pem"
  register: wildcard_key

- name: "Certificates - Define wildcard secret"
  kubernetes.core.k8s:
    state: present
    force: true
    kubeconfig: "{{ k3s_installation_path }}/config"
    definition: 
      apiVersion: v1
      metadata:
        name: wildcard-tls-cert
        namespace: default
      kind: Secret
      type: kubernetes.io/tls
      data:
        tls.crt: "{{ wildcard_cert['content'] }}"
        tls.key: "{{ wildcard_key['content'] }}"

- name: "Certificates - Display mkcert CA file path"
  become: true
  become_user: "{{ k3s_user }}"
  ansible.builtin.shell: mkcert -CAROOT
  register: caroot_file

- name: "Certificates - Slurp ca-crt file"
  become: true
  become_user: "{{ k3s_user }}"
  ansible.builtin.slurp:
    src: "{{ caroot_file.stdout }}/rootCA.pem"
  register: ca_crt

- name: "Certificates - Define CA cert as secret"
  kubernetes.core.k8s:
    state: present
    force: true
    kubeconfig: "{{ k3s_installation_path }}/config"
    definition:
      kind: Secret
      apiVersion: v1
      metadata:
        name: mkcert-ca-cert
        namespace: default
      type: Opaque
      data:
        ca.crt: "{{ ca_crt['content'] }}"
