---
- name: "Traefik - Add https://traefik.github.io/charts repo"
  kubernetes.core.helm_repository:
    name: stable
    repo_url: "https://traefik.github.io/charts"
  tags:
    - k3s-traefik

- name: "Traefik - Deploy traefik helm chart"
  kubernetes.core.helm:
    name: traefik
    chart_ref: stable/traefik
    release_namespace: kube-system
    kubeconfig: "{{ k3s_installation_path }}/config"
    context: local
  tags:
    - k3s-traefik
