---
# tasks file for gpenaud.k3s

- name: "Cluster - Install python kubernetes library"
  become: true
  ansible.builtin.package:
    state: present
    name: "{{ package }}"
  loop:
    - python3-kubernetes
  loop_control:
    loop_var: package

- name: "Cluster - Create k3s directory"
  become: true
  ansible.builtin.file:
    state: directory
    dest: "{{ k3s_installation_path }}"
    owner: "{{ k3s_user }}"
    group: "{{ k3s_user }}"

- name: "Cluster - Add k3s configuration files for control-plane node"
  ansible.builtin.template:
    src: "templates/{{ file }}.j2"
    dest: "{{ k3s_installation_path }}/{{ file }}"
    owner: "{{ k3s_user }}"
    group: "{{ k3s_user }}"
  loop:
    - k3s-config.yml
  loop_control:
    loop_var: file

- name: "Cluster - Install k3s server"
  shell: |
    curl -sfL https://get.k3s.io | sh -s - server --config "{{ k3s_installation_path }}/k3s-config.yml"

- name: "Cluster - Retrieve kubeconfig from remote"
  become: true
  copy:
    src: /etc/rancher/k3s/k3s.yaml
    dest: "{{ k3s_installation_path }}/config"
    remote_src: true
    owner: "{{ k3s_user }}"
    group: "{{ k3s_user }}"

- name: "Cluster - Replace defaults by local in kubeconfigs"
  ansible.builtin.replace:
    path: "{{ k3s_installation_path }}/config"
    regexp: 'default'
    replace: 'local'
