---
- name: "Sealed-Secrets - Add https://bitnami-labs.github.io/sealed-secrets repo"
  kubernetes.core.helm_repository:
    name: sealed-secrets
    repo_url: "https://bitnami-labs.github.io/sealed-secrets"

- name: "Sealed-Secrets - Deploy sealed-secrets helm chart"
  kubernetes.core.helm:
    name: sealed-secrets
    chart_ref: sealed-secrets/sealed-secrets
    release_namespace: kube-system
    kubeconfig: "{{ k3s_installation_path }}/config"
    context: local
    values:
      fullnameOverride: sealed-secrets-controller
